
name: Test the actions

on:
  push:
    paths:
      - test_*.sh
      - join-zt/*

concurrency: one-at-a-time

jobs:
  test-join-zt:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Join ZeroTier network
        uses: ./join-zt
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          api_accesstoken: ${{ secrets.ZEROTIER_API_ACCESSTOKEN }}
      - name: Verify connectivity
        shell: bash
        run: test_connectivity.sh
