
name: Test the actions

on:
  push:
    paths:
      - test_*.sh
      - join-zt/*
      - leave-zt/*

concurrency: one-at-a-time

jobs:
  test-join-zt:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: join-zt
        name: Join ZeroTier network
        uses: ./join-zt
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          api_accesstoken: ${{ secrets.ZEROTIER_API_ACCESSTOKEN }}
          ping_target: emrys.home.zt.ibidem.no
      - name: Verify connectivity
        shell: bash
        run: ./test_connectivity.sh
      - name: Leave ZeroTier network
        if: always()
        uses: ./leave-zt
        with:
          node_id: ${{ steps.join-zt.outputs.node_id }}
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          api_accesstoken: ${{ secrets.ZEROTIER_API_ACCESSTOKEN }}
